---
title: "ff-perf-regression-dashboard-munge"
output: html_notebook
---

Load up the dataset from a pyspark `write.csv`

```{r}
library(lubridate)

df <- NULL
for (file_name in list.files('data', full.names=TRUE, pattern = 'part*')){
  df <- rbind(df, read.csv(file_name))
  # print(head(read.csv(file_name)))
}

df$creation_date <- ymd(df$creation_date)
df$app_build_id <- ymd(df$app_build_id)
```


Retrieve the most current values for each `build_id`

```{r}
library(dplyr)
df_clean <- df %>% group_by(app_build_id, probe) %>% filter(creation_date==max(creation_date)) %>% arrange(desc(app_build_id))
```

```{r}
library('ggplot2')

probe <- unique(df_clean$probe)[2]
probe_df <- df_clean[df_clean$probe==probe, ]
probe_df$thresh <- probe_df$relds_95 >= 0.30

cbPalette <- c("black", "red")
ggplot(probe_df, aes(x=app_build_id, y=relds_5, color=thresh, shape=thresh)) + 
  geom_point(aes(size=probe_df$num_profiles)) +
  geom_errorbar(aes(ymin=relds_25, ymax=relds_95), width=.1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_colour_manual(values=cbPalette) +
  geom_hline(yintercept=0.30, linetype="dashed", color = "red") +
  theme(legend.position="none", panel.background = element_blank(), axis.line = element_line(colour = 'black'))+
  ggtitle(probe)
```

# Probe Histograms
Check out probe histograms
```{r}
library('rjson')
json_file <- '~/tmp/p_hists/probe_hists_20190115.json'
json_data <- fromJSON(file=json_file)
```

# Client Means
Load up the previously processed files
```{r}
load(file = 'data/live/client_means.RData')
```

Let's plot the means through time
```{r}
library(ggplot2)
p <- ggplot(client_means, aes(x=date, y=histogram_parent_fx_page_load_ms_2, 
                    group=interaction(date))) +  
  geom_boxplot(outlier.alpha = 0.1) +
  scale_x_date() 
p
```

